[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/gort/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
  192.168.0.0/24  # Your local home network (adjust if needed)
  10.200.200.0/24  # VPN subnet
  127.0.0.1  # Localhost
  192.168.0.0/16

    FE80::/10
    ::1/128
cors_domains:
    https://app.fluidd.xyz
    https://my.mainsail.xyz
    
#[include octoeverywhere-system.cfg]

[octoprint_compat]

[history]

[timelapse]
output_path: ~/printer_data/timelapse/
frame_path: /tmp/timelapse/printer
enabled: True
ffmpeg_binary_path: /usr/bin/ffmpeg
# frame_limit: 10000 looks depreciated

[update_manager]
channel: dev
refresh_interval: 168

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: ~/mainsail

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[power Printer Power]
type: tasmota
address: 192.168.0.219 #was 219
locked_while_printing: True
restart_klipper_when_powered: True
restart_delay: 1
on_when_job_queued: True
#   If set to True the device will power on if a job is queued while the
#   device is off.  This allows for an automated "upload, power on, and
#   print" approach directly from the slicer, see the configuration example
#   below for details. The default is False.

[file_manager] ##for KAMP
enable_object_processing: True

[update_manager Klipper-Adaptive-Meshing-Purging]
type: git_repo
channel: dev
path: ~/Klipper-Adaptive-Meshing-Purging
origin: https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git
managed_services: klipper
primary_branch: main

# [machine]
# provider: none


