mqtt:
  enabled: false

detectors:
  cpu1:
    type: cpu

record:
  enabled: true
  retain:
    days: 7
    mode: all

# Restream sources via go2rtc
go2rtc:
  streams:
    turret01_main: rtsp://Frigate:uvDSFAvaperjKL@192.168.0.233:554/cam/realmonitor?channel=1&subtype=0
    turret01_sub:  rtsp://Frigate:uvDSFAvaperjKL@192.168.0.233:554/cam/realmonitor?channel=1&subtype=1
    turret02_main: rtsp://Frigate:uvDSFAvaperjKL@192.168.0.185:554/cam/realmonitor?channel=1&subtype=0
    turret02_sub:  rtsp://Frigate:uvDSFAvaperjKL@192.168.0.185:554/cam/realmonitor?channel=1&subtype=1
    turret03_main: rtsp://Frigate:uvDSFAvaperjKL@192.168.0.200:554/cam/realmonitor?channel=1&subtype=0
    turret03_sub:  rtsp://Frigate:uvDSFAvaperjKL@192.168.0.200:554/cam/realmonitor?channel=1&subtype=1

    axis_detect: rtsp://Frigate:uvDSFAvaperjKL@192.168.0.237/axis-media/media.amp?streamprofile=frigate_detect
    axis_view:   rtsp://Frigate:uvDSFAvaperjKL@192.168.0.237/axis-media/media.amp?streamprofile=frigate_view

cameras:
  rpi4_cam:
    enabled: false
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      inputs:
        - path: rtsp://192.168.0.140:8554/picam
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5

  esp32_cam:
    enabled: false
    objects:
      track:
        - person
        - dog
        - cat
    ffmpeg:
      inputs:
        - path: http://192.168.0.222/stream
          input_args:
            - -hide_banner
            - -loglevel
            - warning
            - -analyzeduration
            - "5000000"
            - -probesize
            - "5000000"
            - -fflags
            - nobuffer
            - -flags
            - low_delay
            - -rw_timeout
            - "5000000"
            - -timeout
            - "5000000"
            - -use_wallclock_as_timestamps
            - "1"
            - -f
            - mjpeg
          roles:
            - detect
    record:
      enabled: false
    detect:
      enabled: true
      width: 640
      height: 480
      fps: 3

  Turret_0:
    enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      output_args:
        record:
          - -f
          - segment
          - -segment_time
          - "10"
          - -segment_format
          - mp4
          - -reset_timestamps
          - "1"
          - -strftime
          - "1"
          - -c:v
          - copy
          - -c:a
          - copy
      inputs:
        - path: rtsp://127.0.0.1:8554/turret01_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/turret01_main
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5

  Turret_1:
    enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      output_args:
        record:
          - -f
          - segment
          - -segment_time
          - "10"
          - -segment_format
          - mp4
          - -reset_timestamps
          - "1"
          - -strftime
          - "1"
          - -c:v
          - copy
          - -c:a
          - copy
      inputs:
        - path: rtsp://127.0.0.1:8554/turret02_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/turret02_main
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5

  Turret_2:
    enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      output_args:
        record:
          - -f
          - segment
          - -segment_time
          - "10"
          - -segment_format
          - mp4
          - -reset_timestamps
          - "1"
          - -strftime
          - "1"
          - -c:v
          - copy
          - -c:a
          - copy
      inputs:
        - path: rtsp://127.0.0.1:8554/turret03_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/turret03_main
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 704
      height: 480
      fps: 5

  axis_thermal:
    enabled: true
    objects:
      track:
        - person
        - dog
        - cat
        - car
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/axis_detect
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/axis_view
          input_args: preset-rtsp-restream
          roles:
            - record
    record:
      enabled: true
    detect:
      enabled: true
      width: 768
      height: 576
      fps: 8

version: 0.16-0
