[crowsnest]
log_path: /home/gort/printer_data/logs/crowsnest.log
log_level: verbose
delete_log: false
no_proxy: true

[cam 1]
mode: ustreamer
port: 8088
device: /dev/v4l/by-id/usb-046d_C270_HD_WEBCAM_4751A660-video-index0
resolution: 640x480
max_fps: 10
# v4l2ctl: power_line_frequency=2; brightness=128; contrast=32; saturation=32; sharpness=24; backlight_compensation=1

[cam 2]
mode: ustreamer
port: 8089
device: /dev/v4l/by-id/usb-Generic_USB2.0_PC_CAMERA-video-index0
resolution: 640x480
max_fps: 10
# v4l2ctl: contrast=255
